add mysql example test
aiven/terraform-provider-aiven pull request #1015
Opened 2022-12-28 17:26 UTC by byashimov

## About this change—what it does

Adds mysql example test.

2022-12-28 17:26 UTC, byashimov commented
```
    --- PASS: TestMysqlTestSuite/TestMysql (365.56s)
PASS

Process finished with the exit code 0
```

2022-12-28 20:15 UTC, Serpentiel requested changes

2022-12-28 20:15 UTC, Serpentiel commented on examples_tests/base_test.go
> +func TestExamplesRandPrefix(t *testing.T) {
please comment functions, otherwise lgtm

2022-12-30 12:00 UTC, Serpentiel approved these changes
lgtm

2023-01-02 07:41 UTC, ivan-savciuc approved these changes
LGTM

2023-01-02 07:41 UTC, merged