fix kafka user config with null values only
aiven/terraform-provider-aiven pull request #1035
Opened 2023-01-11 16:20 UTC by byashimov

## About this change—what it does

Fixes service's user config "to api" serialisation. If object has null fields only it's not send nor casted to object.

Resolves #1033

2023-01-11 20:23 UTC, byashimov commented
acc https://github.com/aiven/terraform-provider-aiven/actions/runs/3894704880

2023-01-12 01:56 UTC, Serpentiel requested changes

2023-01-12 01:56 UTC, Serpentiel commented on internal/schemautil/userconfig/apiconvert/toapi.go
> +	if fv == nil {
we would wanna discuss it internally a bit, since it was made this way on purpose in the current version

2023-01-12 09:38 UTC, Serpentiel submitted a review, later dismissed
lgtm

2023-01-12 10:59 UTC, Serpentiel approved these changes
lgtm

2023-01-12 10:59 UTC, merged