feat(userconfig): rich description
aiven/terraform-provider-aiven pull request #1044
Opened 2023-01-23 16:00 UTC by Serpentiel

## About this change—what it does

adds rich description for generated fields

## Why this way

to improve documentation

2023-01-23 17:32 UTC, byashimov requested changes

2023-01-23 17:32 UTC, byashimov commented on docs/resources/kafka.md
> +- `kafka` (Block List, Max: 1) Kafka broker configuration values. The default value is `map[]`. (see [below for nested schema](#nestedblock--kafka_user_config--kafka))
Not sure what should we put here.

2023-01-23 17:32 UTC, byashimov commented on docs/resources/opensearch.md
> +- `max_index_count` (Number, Deprecated) **DEPRECATED: Usage of this field is discouraged.** use index_patterns instead. The default value is `0`.
It is so deprecated. Do we need warn it so many times in a row?

2023-01-23 17:32 UTC, byashimov commented on docs/resources/pg.md
> +- `pg_read_replica` (Boolean) This setting is deprecated. Use read_replica service integration instead.
`Deprecated` is lost.

2023-01-23 17:32 UTC, byashimov commented on docs/resources/pg.md
> +- `pglookout` (Block List, Max: 1) PGLookout settings. The default value is `map[max_failover_replication_time_lag:60]`. (see [below for nested schema](#nestedblock--pg_user_config--pglookout))
Probably must be a json like. Or not displayed at all.

2023-01-23 17:32 UTC, byashimov commented on docs/resources/pg.md
> +- `autodb_idle_timeout` (Number) If the automatically created database pools have been unused this many seconds, they are freed. If 0 then timeout is disabled. [seconds].
Better loose brackets.

2023-01-23 17:32 UTC, byashimov commented on docs/data-sources/account_team_member.md
> +- `team_id` (String) An account team id. This property cannot be changed, doing so forces recreation of the resource.
Please remove trailing dot. That is 80% of diff. Let's make it in a separate PR and focus on default values now.

2023-01-24 11:05 UTC, Serpentiel commented on docs/resources/pg.md
> +- `autodb_idle_timeout` (Number) If the automatically created database pools have been unused this many seconds, they are freed. If 0 then timeout is disabled. [seconds].
will be done in a separate PR

2023-01-24 12:28 UTC, byashimov commented
LGTM.

2023-01-24 12:28 UTC, byashimov approved these changes

2023-01-24 12:28 UTC, merged