ci(acctests): fix flaky tests failing
aiven/terraform-provider-aiven pull request #1049
Opened 2023-01-26 14:46 UTC by Serpentiel

## About this change—what it does

adds an automatic retry for 10 times, if the test resulted in an error

## Why this way

unfortunately, the tests are flaky, but we want to have better view of tests that are actually failing

2023-01-26 14:53 UTC, Serpentiel commented
acceptance tests: https://github.com/aiven/terraform-provider-aiven/actions/runs/4016269696/jobs/6899069511

they should be passing now from the first run

2023-01-26 15:28 UTC, Serpentiel commented on .github/workflows/acceptance-tests.yml
> +          max_attempts: 15
I checked with previous successful runs, it took 6 times to have it to run successfully

2023-02-09 09:55 UTC, mhoffm-aiven commented
Not a fan i have to say, wont that 6x our costs for terraform acceptance tests?

2023-02-09 09:58 UTC, mhoffm-aiven commented
Also if they take 6 times to run through wouldnt a customer also need 6 times to apply a similar manifest?

2023-02-09 10:13 UTC, Serpentiel commented
> Not a fan i have to say, wont that 6x our costs for terraform acceptance tests?

no, insignificantly, yes

2023-02-09 15:29 UTC, mhoffm-aiven commented
Should we retry in the provider more instead of retrying the test?

2023-02-10 09:07 UTC, ivan-savciuc requested changes
I do not think that it is a good idea to rerun flaky tests that often, we should find the root cause and rather fix that. It is going to strange to wait that long and retry 15 times .... not saying about how much cash we are going to burn in the process.

2023-02-10 14:48 UTC, Serpentiel commented
> I do not think that it is a good idea to rerun flaky tests that often, we should find the root cause and rather fix that. It is going to strange to wait that long and retry 15 times .... not saying about how much cash we are going to burn in the process.

we are only rerunning one test three times :)

this has been discussed internally and agreed that we're merging this for dev purposes in v4 branch, and remove this before releasing

2023-02-10 14:48 UTC, merged