chore: deprecate disk_space option
aiven/terraform-provider-aiven pull request #1151
Opened 2023-05-05 15:04 UTC by byashimov

## About this change—what it does

Should be removed a long ago.

2023-05-05 15:08 UTC, mhoffm-aiven commented on internal/schemautil/service.go
> +			Description:   "Additional disk space. Possible values depend on the service type, the cloud provider and the project. Therefore, reducing will result in the service rebalancing.",
Wait isnt it total disk space?

2023-05-05 17:33 UTC, byashimov commented on internal/schemautil/service.go
> +			Description:   "Additional disk space. Possible values depend on the service type, the cloud provider and the project. Therefore, reducing will result in the service rebalancing.",
Thanks.

2023-05-05 19:03 UTC, Serpentiel commented
please fix the [syntax](https://github.com/aiven/terraform-provider-aiven/actions/runs/4896027468/jobs/8742321515?pr=1151#step:4:94) error

2023-05-05 19:04 UTC, Serpentiel requested changes

2023-05-05 19:04 UTC, Serpentiel commented on generator/main.go
> +package main
looks like these files shouldn't be there 🤔

2023-05-10 09:08 UTC, Serpentiel approved these changes
lgtm

2023-05-10 11:10 UTC, merged