feat: organizations support
aiven/terraform-provider-aiven pull request #1172
Opened 2023-05-17 15:00 UTC by Serpentiel

## About this change—what it does

- adds the following resources:

  - `aiven_organization`
  - `aiven_organizational_unit`

  and the corresponding data sources

- deprecates the following field in `aiven_account`:

  - `primary_billing_group_id`
  - `owner_team_id`
  - `tenant_id`

- deprecates `aiven_account_team_project` resource since it won't have any support in future

## Why this way

we are switching away from `aiven_account`

2023-05-17 16:03 UTC, ivan-savciuc requested changes
This PR contains a lot of copy & paste code that could be unified; the org unit is an org resource with the parent_id field, and we can unify a lot of code for these two resources. 

In the future it might be a separate API endpoint but for know I would recommend keep it simple and do not duplicate code.

2023-05-22 14:10 UTC, Serpentiel commented on internal/sdkprovider/service/organization/organization.go
> +	if err := d.Set("organization_id", r.Account.Id); err != nil {
after internally discussing this, we agreed that this is going to be removed, and additionally `account_id` field of the `aiven_account` resource is going to be deprecated

2023-05-22 15:31 UTC, Serpentiel commented
after discussing this internally, we'll leave the duplicated code as-is, since the API is supposed to change very soon

2023-05-23 07:15 UTC, ivan-savciuc submitted a review, later dismissed
LGTM, we better advise customers to use organization and organization unit resources instead of the account that we are deprecating.

2023-05-23 11:28 UTC, merged