feat(organization): user resource and data source
aiven/terraform-provider-aiven pull request #1246
Opened 2023-07-06 12:50 UTC by Serpentiel

## About this change—what it does

adds organization user resource and data source

## Why this way

to have them in place

2023-07-07 10:18 UTC, byashimov requested changes

2023-07-07 10:19 UTC, byashimov commented on internal/sdkprovider/service/organization/organization_user.go
> +
Empty line.

2023-07-07 11:06 UTC, Serpentiel commented on internal/sdkprovider/service/organization/organization_user.go
> +eliminate the member from the organization if one has accepted an invitation previously.
I never wrote this in first place, it’s copy pasted from `aiven_account_team_member` 😃

2023-07-07 11:07 UTC, Serpentiel commented on internal/sdkprovider/service/organization/organization_user.go
> +			}
no

2023-07-07 13:39 UTC, Serpentiel commented on internal/sdkprovider/service/organization/organization_user.go
> +eliminate the member from the organization if one has accepted an invitation previously.
does not works

2023-07-10 07:02 UTC, ivan-savciuc approved these changes
LGTM

2023-07-10 18:47 UTC, merged