feat(plugin): run tests with mux server
aiven/terraform-provider-aiven pull request #1318
Opened 2023-08-24 11:33 UTC by byashimov

## About this change—what it does

Resolves: #xxxxx.

## Why this way

2023-08-24 12:03 UTC, Serpentiel requested changes
we already have `Protov6ProviderFactories` generated in the current version of the code: https://github.com/aiven/terraform-provider-aiven/blob/main/internal/provider/provider_test.go#L19-L25

why don't we simply make variable at line 23 public, and then it will be possible to use it in the tests that are being ran from the SDK provider?

I don't understand why do we need this massive refactoring, when we already have `ProtoV6ProviderFactories` in the current version

2023-08-24 12:35 UTC, Serpentiel requested changes

2023-08-24 12:35 UTC, Serpentiel commented on internal/server/server.go
> +		Name: func() (tfprotov6.ProviderServer, error) {
this should be called `"aiven"`, not `"registry.terraform.io/aiven/aiven"`

2023-08-28 08:09 UTC, byashimov commented
1. [tests](https://github.com/aiven/terraform-provider-aiven/actions/runs/5996656971)
2. [mixed test](https://github.com/aiven/terraform-provider-aiven/actions/runs/5996656971/job/16263108969#step:6:15)

2023-08-28 08:11 UTC, Serpentiel commented on internal/server/server.go
> +package server
nit: comment please

2023-08-28 08:11 UTC, Serpentiel commented on internal/server/server.go
> +func NewMuxServer(ctx context.Context, version string) (tfprotov6.ProviderServer, error) {
nit: comment please

2023-08-28 08:11 UTC, Serpentiel commented on internal/server/server.go
> +
nit: remove NL

2023-08-28 08:11 UTC, Serpentiel commented on internal/server/server.go
> +	return server.ProviderServer(), nil
nit: NL here

2023-08-28 08:12 UTC, Serpentiel commented on main.go
> +
nit: remove NL

2023-08-28 08:12 UTC, Serpentiel commented on internal/acctest/acctest.go
> +	return testAivenClient
nit: remove NL

2023-08-28 09:21 UTC, ivan-savciuc approved these changes
LGTM

2023-08-28 09:21 UTC, ivan-savciuc commented on internal/acctest/acctest.go
> +	return testAivenClient
can you explain please?

2023-08-28 09:22 UTC, ivan-savciuc commented on internal/acctest/acctest.go
> +	return testAivenClient
ah new line I guess :)

2023-08-28 10:17 UTC, byashimov commented on internal/acctest/acctest.go
> +			return server.NewMuxServer(context.Background(), "test")
Well it is never shared. It is used exactly here only.

2023-08-28 10:17 UTC, merged