fix kafka topic creation and read performance
aiven/terraform-provider-aiven pull request #1393
Opened 2023-10-13 09:39 UTC by ivan-savciuc

## About this change—what it does

Fix Kafka Topic create and read performance

2023-10-13 14:37 UTC, byashimov commented
@ivan-savciuc hey is this for v4 or v3, or both?

2023-10-13 14:38 UTC, byashimov submitted a review, later dismissed
lgtm

2023-10-17 01:59 UTC, Serpentiel requested changes

2023-10-17 01:59 UTC, Serpentiel commented on internal/sdkprovider/service/kafkatopic/kafka_topic.go
> +	if isTopicExists(ctx, client, project, serviceName, topicName) {
consider adding a comment above this block to briefly explain its purpose for clarity

2023-10-17 01:59 UTC, Serpentiel commented on internal/sdkprovider/service/kafkatopic/kafka_topic_cache.go
> +func (t *kafkaTopicCache) GetFullQueue(projectName, serviceName string) []string {
ensure the method name accurately represents its purpose; If the function retrieves a specific type of queue or has a unique behavior, be more explicit in the name

2023-10-17 01:59 UTC, Serpentiel commented on internal/sdkprovider/service/kafkatopic/kafka_topic_cache.go
> +	return t.inQueue[projectName+serviceName]
consider handling a scenario where the key might not exist in the `inQueue` map; directly accessing a non-existent key will return a nil slice, which might be unexpected for the function caller

2023-10-17 01:59 UTC, Serpentiel commented on internal/sdkprovider/service/kafkatopic/kafka_topic_exists.go
> +var onceForService sync.Map
consider renaming the variable to be more descriptive, like `onceCheckTopicForService` or something similar

2023-10-17 01:59 UTC, Serpentiel commented on internal/sdkprovider/service/kafkatopic/kafka_topic_exists.go
> +	once.(*sync.Once).Do(func() {
add comments for better clarity, especially on the significance of using `sync.Once`

2023-10-17 01:59 UTC, Serpentiel commented on internal/sdkprovider/service/kafkatopic/kafka_topic_exists.go
> +	if err != nil {
this approach can be confusing: if possible, consider handling the error within the `once.Do` block, or refactoring the approach to make the flow clearer

2023-10-17 01:59 UTC, Serpentiel commented on internal/sdkprovider/service/kafkatopic/kafka_topic_exists.go
> +	if slices.Contains(c.GetV1List(project, serviceName), topic) || slices.Contains(c.GetFullQueue(project, serviceName), topic) {
for better performance, if the topic is found in the first `c.GetV1List` check, there's no need to check in the second `c.GetFullQueue` call: you can return `true` immediately

2023-10-23 07:15 UTC, ivan-savciuc commented
Converting this patch for v4 instead of v5 (current master), will open another RP

2023-10-23 07:15 UTC, closed without merging