chore(org): add support for org group projects
aiven/terraform-provider-aiven pull request #1496
Opened 2023-12-28 17:14 UTC by ivan-savciuc

## About this change—what it does

Adding support for organization group project permissions

2023-12-28 22:31 UTC, Serpentiel approved these changes
lgtm but please check the review below

2023-12-28 22:31 UTC, Serpentiel commented on internal/plugin/service/organization/organization_group_project_test.go
> +	if orgID == "" {
please replace with `os.LookupEnv`

2023-12-28 22:31 UTC, Serpentiel commented on internal/plugin/service/organization/organization_group_project_test.go
> +	if os.Getenv("PROVIDER_AIVEN_ENABLE_BETA") == "" {
same as above

2023-12-28 22:31 UTC, Serpentiel requested changes
please address the above review comments

2023-12-28 22:34 UTC, Serpentiel submitted a review, later dismissed

2023-12-28 22:34 UTC, Serpentiel commented on go.mod
> +	github.com/aiven/aiven-go-client/v2 v2.5.1-0.20231228170105-c4df0fe534c0
please use `v2.6.0`; setting this to a fixed commit will break dependabot's automatic updates

2023-12-29 08:17 UTC, ivan-savciuc commented on internal/plugin/service/organization/organization_group_project_test.go
> +	if os.Getenv("PROVIDER_AIVEN_ENABLE_BETA") == "" {
updated with the os.LookupEnv

2023-12-30 05:17 UTC, Serpentiel approved these changes
lgtm

2023-12-30 05:17 UTC, merged