test: add vpc sweepers
aiven/terraform-provider-aiven pull request #1524
Opened 2024-01-11 08:42 UTC by ivan-savciuc

## About this change—what it does

Add sweepers for VPC package resources

2024-01-11 15:47 UTC, Serpentiel requested changes
some minor changes

2024-01-11 15:47 UTC, Serpentiel commented on internal/sdkprovider/service/vpc/sweep.go
> +
remove new line

2024-01-11 15:47 UTC, Serpentiel commented on internal/sdkprovider/service/vpc/sweep.go
> +			if err != nil && !aiven.IsNotFound(err) {
let's do this: https://github.com/aiven/terraform-provider-aiven/pull/1525#discussion_r1448996423

2024-01-12 07:54 UTC, ivan-savciuc commented
@Serpentiel waiting for this merger first https://github.com/aiven/terraform-provider-aiven/pull/1525 to avoid conflicts

2024-01-12 08:36 UTC, Serpentiel commented
@ivan-savciuc done

2024-01-12 09:08 UTC, closed without merging

2024-01-12 09:12 UTC, Serpentiel commented
duplicates #1529