feat: thanos support
aiven/terraform-provider-aiven pull request #1702
Opened 2024-04-22 14:35 UTC by Serpentiel

## About this change—what it does

- Add Thanos resource (`aiven_thanos`) to allow for the creation and management of Thanos services

## Why this way

🚀

2024-04-24 07:54 UTC, byashimov requested changes

2024-04-24 08:01 UTC, Serpentiel commented on internal/sdkprovider/service/thanos/thanos.go
> +		Description:   "Creates and manages an [Aiven for Metrics®](https://aiven.io/docs/products/metrics/concepts/metrics-overview) service.",
I remember doing that. No idea why it's not there. I'll update the PR.

2024-04-24 10:18 UTC, byashimov commented
I have created Thanos in the Console, it has connection info fields:
<img width="228" alt="image" src="https://github.com/aiven/terraform-provider-aiven/assets/1560043/79f707ef-e792-4e35-8f26-69ff8cdf0185">

I believe we should proxy them to the resource.

2024-04-25 14:18 UTC, Serpentiel commented
Temporarily marked as draft. Some things should be clarified.

2024-04-29 13:38 UTC, byashimov commented on internal/sdkprovider/service/thanos/thanos_test.go
> +      query_range_align_range_with_step = true
true is default value, might give a false positive

2024-04-29 13:39 UTC, byashimov approved these changes
lgtm

2024-04-30 10:25 UTC, merged