feat(aiven_organization_application_user): SDKv2, add is_super_admin
aiven/terraform-provider-aiven pull request #1736
Opened 2024-05-27 08:03 UTC by byashimov

- Removes beta flag from the user datasource (tech debt)
- Rewrites app users to sdkv2
- Adds `is_super_admin` flag

2024-05-27 09:55 UTC, byashimov commented
[tests](https://github.com/aiven/terraform-provider-aiven/actions/runs/9251982828)

2024-05-27 13:00 UTC, staceysalamon-aiven requested changes
Small suggestion for the field description to match the Console docs.

2024-05-28 05:06 UTC, rriski approved these changes

2024-05-28 06:49 UTC, byashimov commented on docs/data-sources/organization_application_user.md
> +- `is_super_admin` (Boolean) Alters super admin state of the organization application user.
Thanks Stacey!

2024-05-28 07:11 UTC, rriski approved these changes

2024-05-28 07:14 UTC, staceysalamon-aiven submitted a review, later dismissed
LGTM

2024-05-28 08:31 UTC, rriski approved these changes

2024-05-28 09:13 UTC, merged