change Kafka Topic resource behaviour
aiven/terraform-provider-aiven pull request #325
Opened 2020-09-29 14:16 UTC by ivan-savciuc

change Kafka Topic resource `retention_hours` behaviour according to API specification

2020-09-29 14:41 UTC, ivan-savciuc commented
Ok I see, then I'll change that as well

2020-09-29 15:27 UTC, ivan-savciuc commented
Updated PR using latest go-client with `retention_hours` as an optional field.

2020-09-29 17:35 UTC, rikonen requested changes
-1 handling doesn't look correct

2020-09-29 17:35 UTC, rikonen commented on aiven/resource_kafka_topic.go
> +		ValidateFunc: validation.IntBetween(0, 2562047788015),
-1 is valid value, means infinite retention

2020-09-29 17:35 UTC, rikonen commented on aiven/resource_kafka_topic.go
> +			if old == "-1" {
This doesn't look correct as -1 doesn't mean not defined.

2020-09-29 17:35 UTC, rikonen commented on aiven/resource_kafka_topic.go
> +		// it could be -1, which means that this field is not defined.
Means retention time is infinite

2020-09-30 10:24 UTC, rikonen approved these changes

2020-09-30 10:24 UTC, merged