change service integration behaviour
aiven/terraform-provider-aiven pull request #534
Opened 2021-07-23 15:29 UTC by ivan-savciuc

In some cases, service creation may trigger the creation of service integration. For example, PG read replica service integration does that. PG replica service is created with service integration user configuration options that trigger the creation of service integration. To handle such cases correctly, we update the creation logic for the service_integration resource; it should work correctly when a service integration already exists.

2021-07-30 06:25 UTC, encima submitted a review, later dismissed
Only tested by running tests existing. Check for adding integrations to already running services makes sense but would have liked to test. Approving now as I am holding up the release. Will merge by EOD unless more stringent checks are needed and then I will make time on Monday

2021-07-30 07:03 UTC, ivan-savciuc commented
Updated this branch with the latest master changer

2021-08-06 13:54 UTC, mhoffm-aiven requested changes
purely cosmetical, but could we separate stdlib imports from external imports?

2021-08-06 15:00 UTC, ivan-savciuc commented
> purely cosmetical, but could we separate stdlib imports from external imports?

sure, will do, I'll try to configure my IDE so it can do that automatically

2021-08-09 13:58 UTC, mhoffm-aiven approved these changes

2021-08-09 14:58 UTC, merged