add opensearch support
aiven/terraform-provider-aiven pull request #562
Opened 2021-09-10 16:06 UTC by ivan-savciuc

2021-09-10 16:27 UTC, mhoffm-aiven requested changes

2021-09-10 16:27 UTC, mhoffm-aiven commented on aiven/resource_opensearch.go
> +				"kibana_uri": {
is it still kibana in open search?

2021-09-10 16:27 UTC, mhoffm-aiven commented on aiven/resource_service.go
> +	case "opensearch":
probably the kibana_uri missing?

2021-09-13 06:31 UTC, ivan-savciuc commented on aiven/resource_opensearch.go
> +				"kibana_uri": {
indeed no kibana, double checked

2021-09-13 13:03 UTC, mhoffm-aiven approved these changes
lgtm

2021-09-13 13:08 UTC, merged