add azure privatelink support
aiven/terraform-provider-aiven pull request #576
Opened 2021-10-01 12:00 UTC by ivan-savciuc

2021-10-01 12:58 UTC, mhoffm-aiven requested changes

2021-10-01 12:58 UTC, mhoffm-aiven commented on aiven/resource_azure_privatelink.go
> +		Timeout:    d.Timeout(schema.TimeoutCreate),
could be `schema.TimeoutRead`

2021-10-04 07:21 UTC, ivan-savciuc commented on aiven/resource_azure_privatelink.go
> +		Timeout:    d.Timeout(schema.TimeoutCreate),
done

2021-10-04 12:22 UTC, ivan-savciuc commented
added deletion waiter

2021-10-05 07:39 UTC, mhoffm-aiven approved these changes
lgtm

2021-10-05 07:43 UTC, merged