add support for dynamic disk size
aiven/terraform-provider-aiven pull request #605
Opened 2021-11-02 13:39 UTC by mhoffm-aiven

This PR adds support for dynamic disk size in service creation and updates

2021-11-05 09:54 UTC, mhoffm-aiven commented
Acceptance Test Failure  seems related to flakiness of the mysql service test.

2021-11-08 14:05 UTC, rikonen requested changes
I didn't read quite to the end because the service types call is a no go and I'm not sure how much this will have to change when working around that.

2021-11-08 15:28 UTC, mhoffm-aiven commented on aiven/provider.go
> +func diskSpaceDiffSuppressFunc(_, o, n string, d *schema.ResourceData) bool {
i tried to avoid new because its a keyword; should i change anyway?

2021-11-08 15:31 UTC, mhoffm-aiven commented on aiven/resource_service.go
> +	serviceTypesResponse, err := client.ServiceTypes.Get(project)
I mean; it would be nicer to have a more fine grained api call for that where we do not have to filter on the client side

2021-11-08 15:32 UTC, mhoffm-aiven commented on aiven/resource_pg_test.go
> +      disk_space = "90GiB"
:heavy_check_mark:

2021-11-08 15:37 UTC, mhoffm-aiven commented on aiven/provider.go
> +	ob, _ := units.RAMInBytes(o)
both are already validated at this point by the `validateHumanByteSizeString` function

2021-11-08 15:44 UTC, mhoffm-aiven commented on aiven/datasource_service.go
> +			}
:heavy_check_mark:

2021-11-08 15:47 UTC, mhoffm-aiven commented on Makefile
> +	TF_ACC=1 CGO_ENABLED=0 go test -failfast -v -count 1 -parallel 25 --cover ./... -timeout 120m
:heavy_check_mark:

2021-11-08 17:22 UTC, rikonen commented on aiven/provider.go
> +func diskSpaceDiffSuppressFunc(_, o, n string, d *schema.ResourceData) bool {
I think `new` is used in the existing diff suppress funcs already

2021-11-08 17:23 UTC, rikonen submitted a review, later dismissed
Discussed elsewhere, we'll add some sort of caching for the service types response until we've introduced new API that allows getting only the relevant info instead of all info for all possible clouds, plans and service types.

2021-11-26 13:22 UTC, ivan-savciuc reviewed
Looks good, found just some minor things, in general if we can use a shorter names for the functions that would be great.

2021-11-26 13:22 UTC, ivan-savciuc commented on aiven/resource_service.go
> +func resourceServiceCustomizeDiffWrapper(serviceType string) schema.CustomizeDiffFunc {
And lastly `customdiff.All` combines all the errors from the checks, and your will see many of them at once if that is the case.

2021-11-26 13:22 UTC, ivan-savciuc commented on aiven/resource_service.go
> +func resourceServiceCustomizeDiffCheckNoNewServiceIntegrationAfterCreation(ctx context.Context, d *schema.ResourceDiff, m interface{}) error {
looks like that we are not using a `context` here, do we need it? At least we can use a `_`

2021-11-26 13:41 UTC, mhoffm-aiven commented on aiven/provider.go
> +type resourceStateOrResourceDiff interface {
its used, because we need to fetch service plans from the resource diff ( for customize diff ) or the schema ( in the regular create/update )

2021-11-26 14:34 UTC, ivan-savciuc approved these changes
Except some minor things from above it LGTM and works well

2021-11-30 08:14 UTC, mhoffm-aiven commented
Cleanup will be defered to a different PR

2021-11-30 08:14 UTC, merged