update examples, set v3 or provider
aiven/terraform-provider-aiven pull request #891
Opened 2022-09-09 11:29 UTC by byashimov

## About this change—what it does

Updates examples with v3 provider version.

2022-09-09 12:08 UTC, Serpentiel requested changes
there might be some chance that these examples won't exactly work with v3.x of our provider

also, at least one of these resources should be removed, that is the `elasticsearch` resource, and we should probably update it to use `opensearch`

we should probably discuss this a bit more before proceeding next

2022-09-09 12:08 UTC, Serpentiel commented on CHANGELOG.md
> +
please move all these changes under `[MAJOR.MINOR.PATCH] - YYYY-MM-DD` section

2022-09-09 12:08 UTC, Serpentiel commented on CHANGELOG.md
> +
please move all these changes under `[MAJOR.MINOR.PATCH] - YYYY-MM-DD` section
we add version number when we're ready to release

2022-09-12 17:42 UTC, ivan-savciuc requested changes
Just a minor thing, can you put a space in between `>=` and the version?

2022-09-21 07:34 UTC, ivan-savciuc commented
@byashimov can you check comments for this PR please?

2022-10-06 15:45 UTC, closed without merging