feat: add support for properties like ip_filter
aiven/terraform-provider-aiven pull request #907
Opened 2022-09-29 16:45 UTC by Serpentiel

# ONLY MERGE AFTER #904

## About this change—what it does

adds support for properties like `ip_filter`

## Why this way

to support them

2022-09-29 17:15 UTC, ivan-savciuc requested changes
When checking `terraform schema` getting: 
```
"ip_filter": {
              "type": "string",
              "description": "Allow incoming connections from CIDR address block, e.g. '10.20.0.0/16'",
              "description_kind": "plain",
              "optional": true
            },
```

And also this in the schema:
```
"ip_filter": {
			Description: "Allow incoming connections from CIDR address block, e.g. '10.20.0.0/16'",
			Optional:    true,
			Type:        schema.TypeString,
		},
```

2022-10-03 14:05 UTC, Serpentiel commented
> When checking `terraform schema` getting:
> 
> ```
> "ip_filter": {
>               "type": "string",
>               "description": "Allow incoming connections from CIDR address block, e.g. '10.20.0.0/16'",
>               "description_kind": "plain",
>               "optional": true
>             },
> ```
> 
> And also this in the schema:
> 
> ```
> "ip_filter": {
> 			Description: "Allow incoming connections from CIDR address block, e.g. '10.20.0.0/16'",
> 			Optional:    true,
> 			Type:        schema.TypeString,
> 		},
> ```

this has been resolved, please check again

2022-10-04 18:05 UTC, ivan-savciuc approved these changes
LGTM

2022-10-04 18:05 UTC, ivan-savciuc commented on internal/schemautil/user_config/service_types.go
> +			Type:     schema.TypeList,
can we use `schema,TypeSet` instead of list for the ip_filter string

2022-10-05 06:39 UTC, merged