Added missing OpenSearch external integration endpoint schema
aiven/terraform-provider-aiven pull request #946
Opened 2022-11-01 02:04 UTC by joshua-rule

## About this change—what it does
Adds the OpenSearch schema for external integration endpoints which is currently missing and a customer would like to use

2022-11-01 13:15 UTC, Serpentiel requested changes
please add changelog entry, otherwise lgtm

2022-11-02 00:28 UTC, joshua-rule commented
> please add changelog entry, otherwise lgtm

Added chagelog entry

2022-11-02 09:01 UTC, Serpentiel commented
> Added chagelog entry

ahh, dayum, `make docs` also wants to be run

2022-11-02 09:02 UTC, Serpentiel submitted a review, later dismissed
> Added chagelog entry

ahh, dayum, `make docs` also wants to be run before we can merge this

lgtm

2022-11-02 23:14 UTC, joshua-rule commented
> > Added chagelog entry
> 
> ahh, dayum, `make docs` also wants to be run before we can merge this
> 
> lgtm

Done github had the failed check hidden at the bottom of the scroll so missed it my bad :joy_cat:

2022-11-03 09:22 UTC, Serpentiel approved these changes
lgtm

2022-11-03 09:22 UTC, merged